name: 'Build skia on mac'
on:
    workflow_dispatch:
    
permissions:
  contents: read
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: macos-latest
    steps:
        - name: "Check out repo's default branch"
          uses: actions/checkout@v3
        - name: 'execute python build script'
          run:  python3 scripts/main.py
          shell: sh
