name: 'Build skia on ubuntu'
on:
    workflow_dispatch:
    
permissions:
  contents: read
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: ubuntu-latest
    steps:
        # - name: "install development packages"
        #   run: sudo apt install build-essential clang libfontconfig-dev libjpeg-dev libharfbuzz-dev  mesa-common-dev libwebp-dev
        # - name: "Check out repo's default branch"
        #   uses: actions/checkout@v3
        # - name: 'execute python build script'
        #   run:  python3 -u scripts/main.py
        #   shell: sh
        - name: 'create simple file'
          run:  touch ${HOME}/skia_linux_x64_clang_release.tar.gz
          shell: sh
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ${HOME}/skia_linux_x64_clang_release.tar.gz
            asset_name: skia_linux_x64_clang_release
            tag: weekly
            overwrite: true
