name: 'Build skia on mac'
on:
    workflow_dispatch:
    
permissions:
  contents: read
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: macos-latest
    steps:
        - name: "Check out repo's default branch"
          uses: actions/checkout@v3
        - name: 'execute python build script'
          run:  python3 -u scripts/main.py
          shell: sh
        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: /home/runner/PROJECTS/GOOGLE/skia/skia_macos_x64_clang_release.tar.gz
            asset_name: skia_macos_x64_clang_release.tar.gz
            tag: refs/tags/weekly
            overwrite: true
