name: 'Build skia on windows'
on:
    workflow_dispatch:
    
permissions:
  contents: write
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: windows-2019	
    steps:
        - name: "Check out repo's default branch"
          uses: actions/checkout@v3
        - name: 'execute python build script'
          shell: pwsh
          run:  python -u scripts/main.py
