name: 'Build skia on windows'
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 6"
    
permissions:
  contents: write
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: windows-2022
    steps:
        - name: "Check out repo's default branch"
          uses: actions/checkout@v3
        - name: Install LLVM and Clang
          uses: KyleMayes/install-llvm-action@v1
          with:
            version: "15.0.7"
        - name: 'Check clang version'
          shell: cmd
          run:  clang --version
        - name: 'execute python build script'
          shell: pwsh
          run:  python -u scripts/main.py
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: Upload windows debug and release binaries to releases
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: C:\Users\runneradmin\PROJECTS\GOOGLE\skia\skia_win_x64_clang_debug_and_release.zip
            asset_name: skia_win_x64_clang_debug_and_release.zip
            tag: refs/tags/weekly-${{ steps.date.outputs.date }}
            overwrite: true
