name: 'Build skia on windows'
on:
    workflow_dispatch:
    
permissions:
  contents: read
  issues: write
  
jobs:
  setup_depot_tools_and_build_skia:
    name: 'Setup depot tools and build skia'
    runs-on: windows-latest
    steps:
        - name: "Check out repo's default branch"
          uses: actions/checkout@v3
        - name: 'execute windows batch file'
          run:  cmd /c "build_windows.bat"
